namespace Common.Constants;

public class TagLists
{
    public List<string> GenreList { get; } = new()
    {
        "18th century",
        "19th century",
        "20th century",
        "academic",
        "action",
        "adventure",
        "africa",
        "african american",
        "african literature",
        "aliens",
        "alternate history",
        "american",
        "american civil war",
        "american history",
        "american revolution",
        "ancient",
        "ancient history",
        "angels",
        "animals",
        "anthologies",
        "anthropology",
        "apocalyptic",
        "art",
        "arthurian",
        "asia",
        "asian literature",
        "astronomy",
        "atheism",
        "australia",
        "autobiography",
        "aviation",
        "banned books",
        "biblical",
        "biblical fiction",
        "biography",
        "biography memoir",
        "biology",
        "book club",
        "books about books",
        "botswana",
        "british literature",
        "buddhism",
        "business",
        "canada",
        "cats",
        "chapter books",
        "chick lit",
        "childrens",
        "childrens classics",
        "china",
        "christian",
        "christian fiction",
        "christian romance",
        "christianity",
        "christmas",
        "church",
        "civil war",
        "classic literature",
        "classics",
        "collections",
        "college",
        "comedy",
        "comic book",
        "comic strips",
        "comics",
        "coming of age",
        "communication",
        "contemporary",
        "contemporary romance",
        "cooking",
        "counting",
        "crime",
        "cyberpunk",
        "czech literature",
        "dark",
        "death",
        "demons",
        "detective",
        "dinosaurs",
        "disability",
        "dogs",
        "dragons",
        "drama",
        "dystopia",
        "eastern philosophy",
        "economics",
        "education",
        "egypt",
        "english literature",
        "environment",
        "epic",
        "epic fantasy",
        "espionage",
        "essays",
        "ethiopia",
        "european history",
        "evolution",
        "fae",
        "fairies",
        "fairy tales",
        "faith",
        "family",
        "fantasy",
        "feminism",
        "fiction",
        "fighters",
        "finance",
        "folklore",
        "food",
        "france",
        "french literature",
        "french revolution",
        "futuristic",
        "gender",
        "german literature",
        "germany",
        "ghosts",
        "gothic",
        "graphic novels",
        "graphic novels comics",
        "greece",
        "greek mythology",
        "halloween",
        "health",
        "high fantasy",
        "high school",
        "historical",
        "historical fiction",
        "historical romance",
        "history",
        "holiday",
        "holocaust",
        "horror",
        "horse racing",
        "horses",
        "humor",
        "india",
        "indian literature",
        "inspirational",
        "ireland",
        "irish literature",
        "islam",
        "israel",
        "italian literature",
        "italy",
        "japan",
        "japanese literature",
        "jewish",
        "journalism",
        "judaism",
        "juvenile",
        "kids",
        "latin american",
        "law",
        "lds",
        "leadership",
        "legal thriller",
        "lgbt",
        "literary fiction",
        "literature",
        "love",
        "love story",
        "magic",
        "magical realism",
        "management",
        "mathematics",
        "media tie in",
        "medical",
        "medicine",
        "medieval",
        "memoir",
        "mental health",
        "mental illness",
        "middle grade",
        "military fiction",
        "modern classics",
        "monsters",
        "mountaineering",
        "music",
        "mystery",
        "mystery thriller",
        "mythology",
        "native americans",
        "nature",
        "new adult",
        "new age",
        "new york",
        "nigeria",
        "nobel prize",
        "noir",
        "nonfiction",
        "novels",
        "nutrition",
        "pakistan",
        "paranormal",
        "paranormal romance",
        "personal development",
        "philosophy",
        "physics",
        "picture books",
        "pirates",
        "plays",
        "poetry",
        "political science",
        "politics",
        "popular science",
        "portugal",
        "portuguese literature",
        "post apocalyptic",
        "prehistoric",
        "presidents",
        "productivity",
        "psychological thriller",
        "psychology",
        "queer",
        "race",
        "read for school",
        "realistic fiction",
        "reference",
        "regency",
        "relationships",
        "religion",
        "retellings",
        "road trip",
        "robots",
        "romance",
        "romanticism",
        "russia",
        "russian literature",
        "scandinavian literature",
        "school",
        "science",
        "science fiction",
        "science fiction fantasy",
        "scotland",
        "self help",
        "short stories",
        "social justice",
        "social science",
        "sociology",
        "south africa",
        "southern",
        "southern gothic",
        "space",
        "space opera",
        "spain",
        "spanish literature",
        "speculative fiction",
        "spirituality",
        "sports",
        "steampunk",
        "storytime",
        "superheroes",
        "supernatural",
        "survival",
        "suspense",
        "sweden",
        "swedish literature",
        "taoism",
        "teen",
        "the united states of america",
        "theatre",
        "theology",
        "theory",
        "thriller",
        "time travel",
        "tragedy",
        "travel",
        "travelogue",
        "true crime",
        "true story",
        "tudor period",
        "unfinished",
        "unicorns",
        "urban fantasy",
        "vampires",
        "victorian",
        "war",
        "werewolves",
        "westerns",
        "witches",
        "womens",
        "world war i",
        "world war ii",
        "writing",
        "young adult",
        "young adult contemporary",
        "young adult fantasy",
        "young adult romance",
        "zombies"
    };
    
    public List<string> AuthorList { get; } = new()
    {
        "A.A. Milne",
        "Abraham Verghese",
        "Agatha Christie",
        "Albert Camus",
        "Aldous Huxley",
        "Alexandre Dumas",
        "Alice Sebold",
        "Alice Walker",
        "Allen Ginsberg",
        "Ally Carter",
        "Ally Condie",
        "Amy Tan",
        "Andrew Davidson",
        "Andy Weir",
        "Angie Thomas",
        "Anne Frank",
        "Anne Morrow Lindbergh",
        "Anne Rice",
        "Anthony Burgess",
        "Antoine de Saint-Exupéry",
        "Arthur C. Clarke",
        "Arthur Conan Doyle",
        "Arthur Golden",
        "Art Spiegelman",
        "Astrid Lindgren",
        "Ayn Rand",
        "Barbara Kingsolver",
        "Beatrice Sparks",
        "Becca Fitzpatrick",
        "Benjamin Alire Sáenz",
        "Bernhard Schlink",
        "Betty Smith",
        "Bill Bryson",
        "Bill Watterson",
        "Bram Stoker",
        "Brandon Sanderson",
        "Brett Easton Ellis",
        "Bryce Courtenay",
        "C.S. Lewis",
        "Carl Sagan",
        "Carlos Ruiz Zafón",
        "Cassandra Clare",
        "Cecelia Ahern",
        "Chaim Potok",
        "Charles Darwin",
        "Charles Dickens",
        "Charlotte Brontë",
        "Charlotte Perkins Gilman",
        "Chuck Palahniuk",
        "Colleen Hoover",
        "Colleen McCullough",
        "Cormac McCarthy",
        "Corrie ten Boom",
        "D.H. Lawrence",
        "Dan Brown",
        "Daniel Defoe",
        "Dante Alighieri",
        "Daphne du Maurier",
        "Dave Eggers",
        "David Foster Wallace",
        "David McCullough",
        "David Mitchell",
        "David Sedaris",
        "Dean Koontz",
        "Diana Forbes",
        "Diana Gabaldon",
        "Diane Setterfield",
        "Diamante Lavendar",
        "Dodie Smith",
        "Douglas Adams",
        "Dr. Seuss",
        "E.B. White",
        "Edgar Allan Poe",
        "Edith Hamilton",
        "Edith Wharton",
        "E.L. James",
        "Elizabeth Gilbert",
        "Elizabeth Kostova",
        "Ellen Raskin",
        "Emily Brontë",
        "Emily Dickinson",
        "Emma Donoghue",
        "Eric Carle",
        "Erich Maria Remarque",
        "Erich Segal",
        "Ernest Cline",
        "Ernest Hemingway",
        "Evelyn Waugh",
        "F. Scott Fitzgerald",
        "Fannie Flagg",
        "Frances Hodgson Burnett",
        "Frank McCourt",
        "Frank Herbert",
        "Franz Kafka",
        "Fyodor Dostoyevsky",
        "Gabriel García Márquez",
        "Gaston Leroux",
        "Geoffrey Chaucer",
        "George Eliot",
        "George Orwell",
        "George R.R. Martin",
        "Gillian Flynn",
        "Gregory David Roberts",
        "Gregory Maguire",
        "Gustave Flaubert",
        "H.G. Wells",
        "Harlan Ellison",
        "Harper Lee",
        "Harriet Beecher Stowe",
        "Helen Fielding",
        "Helen Keller",
        "Hermann Hesse",
        "Homer",
        "Howard Zinn",
        "Hunter S. Thompson",
        "Isabel Allende",
        "Isaac Asimov",
        "Italo Calvino",
        "J.D. Salinger",
        "J.K. Rowling",
        "J.M. Barrie",
        "J.R.R. Tolkien",
        "J.R. Ward",
        "Jack Kerouac",
        "Jack London",
        "James Clavell",
        "James Dashner",
        "James Joyce",
        "Janet Evanovich",
        "Jay Asher",
        "Jean M. Auel",
        "Jeaniene Frost",
        "Jeffrey Archer",
        "Jeffrey Eugenides",
        "Jenny Han",
        "Jerry B. Jenkins",
        "Jerry Spinelli",
        "Jhumpa Lahiri",
        "John Berendt",
        "John Boyne",
        "John Green",
        "John Grisham",
        "John Irving",
        "John Kennedy Toole",
        "John Knowles",
        "John Milton",
        "John Steinbeck",
        "Jonathan Safran Foer",
        "Jonathan Swift",
        "Jorge Luis Borges",
        "Joseph Campbell",
        "Joseph Conrad",
        "Joseph Heller",
        "Judy Blume",
        "Jules Verne",
        "Karen Marie Moning",
        "Kate Chopin",
        "Kate DiCamillo",
        "Kathryn Stockett",
        "Ken Follett",
        "Ken Kesey",
        "Kenneth Grahame",
        "Khaled Hosseini",
        "Ki Longfellow",
        "Kurt Vonnegut Jr.",
        "L.M. Montgomery",
        "Laura Esquivel",
        "Laura Hillenbrand",
        "Lauren Kate",
        "Lauren Oliver",
        "Leigh Bardugo",
        "Leo Tolstoy",
        "Lewis Carroll",
        "Lisa Genova",
        "Lois Lowry",
        "Louis de Bernières",
        "Louisa May Alcott",
        "Madeline Miller",
        "Madeleine L'Engle",
        "Marcel Proust",
        "Marcus Zusak",
        "Margaret Atwood",
        "Margaret Mitchell",
        "Margaret Wise Brown",
        "Maria V. Snyder",
        "Marissa Meyer",
        "Mark Haddon",
        "Mark Twain",
        "Mary Ann Shaffer",
        "Mary Doria Russell",
        "Mary Shelley",
        "Mary Wollstonecraft Shelley",
        "Maurice Sendak",
        "Max Brooks",
        "Michael Chabon",
        "Michael Crichton",
        "Michael Ende",
        "Michael Ondaatje",
        "Michael Pollan",
        "Milan Kundera",
        "Mitch Albom",
        "Muriel Barbery",
        "Neal Shusterman",
        "Neal Stephenson",
        "Neil Gaiman",
        "Nicholas Sparks",
        "Nick Hornby",
        "Nicole Krauss",
        "Norton Juster",
        "Oliver Ann Burns",
        "Orson Scott Card",
        "Oscar Wilde",
        "Pat Conroy",
        "Patrick Rothfuss",
        "Patrick Süskind",
        "Paulo Coelho",
        "Pearl S. Buck",
        "Peter S. Beagle",
        "Philip K. Dick",
        "Philip Pullman",
        "Philippa Gregory",
        "Pierre Boulle",
        "Plato",
        "P.L. Travers",
        "Rainbow Rowell",
        "Randy Pausch",
        "Ray Bradbury",
        "Rebecca Wells",
        "Richard Adams",
        "Richard Bach",
        "Richard Matheson",
        "Richard Wright",
        "Rick Riordan",
        "Richelle Mead",
        "Robert A. Heinlein",
        "Robert Frost",
        "Robert Graves",
        "Robert Louis Stevenson",
        "Robert M. Pirsig",
        "Rohinton Mistry",
        "Rudyard Kipling",
        "Salman Rushdie",
        "Samuel Beckett",
        "Sara Gruen",
        "Sarah Dessen",
        "Sarah J. Maas",
        "Scott Lynch",
        "Scott O'Dell",
        "Scott Westerfeld",
        "Sharon Creech",
        "Shel Silverstein",
        "Shirley Jackson",
        "Simone Elkeles",
        "Sophie Kinsella",
        "Sophocles",
        "Stephen Hawking",
        "Stephen King",
        "Stephenie Meyer",
        "Steve Snyder",
        "Stieg Larsson",
        "Sue Monk Kidd",
        "Sun Tzu",
        "Suzanne Boisvert",
        "Suzanne Collins",
        "Sylvia Day",
        "Sylvia Plath",
        "Sylvain Reynard",
        "Terry Goodkind",
        "Terry Pratchett",
        "Thomas Hardy",
        "Thomas Mann",
        "Thomas Pynchon",
        "Tim Butcher",
        "Tim O'Brien",
        "Tom Robbins",
        "Toni Morrison",
        "Tracy Chevalier",
        "Truman Capote",
        "Umberto Eco",
        "Upton Sinclair",
        "Ursula K. Le Guin",
        "Victor Hugo",
        "Virginia Woolf",
        "Vladimir Nabokov",
        "Voltaire",
        "V.C. Andrews",
        "W. Bruce Cameron",
        "Wallace Stegner",
        "Wally Lamb",
        "Walt Whitman",
        "Walter M. Miller Jr.",
        "Walter Scott",
        "W.E.B. Du Bois",
        "William Faulkner",
        "William Gibson",
        "William Goldman",
        "William Paul Young",
        "William Peter Blatty",
        "William Shakespeare",
        "William Styron",
        "Wilson Rawls",
        "Winston Groom",
        "Willa Cather",
        "Wilkie Collins",
        "Yann Martel",
        "Zora Neale Hurston"
    };

    public List<string> StudioList { get; } = new()
    {
        "20th Century Studios",
        "A24",
        "Columbia Pictures",
        "DreamWorks Pictures",
        "Lionsgate Films",
        "Marvel Studios",
        "New Line Cinema",
        "Paramount Pictures",
        "Pixar Animation Studios",
        "Universal Pictures",
        "Walt Disney Pictures",
        "Warner Bros. Pictures"
    };

    public List<string> DirectorList { get; } = new()
    {
        "Andrew Adamson",
        "Chris Columbus",
        "Daniel Kwan",
        "Daniel Scheinert",
        "David Fincher",
        "David Silverman",
        "Gary Ross",
        "James Cameron",
        "Jon Favreau",
        "Justin Lin",
        "Lee Unkrich",
        "Neil Burger",
        "Pete Docter",
        "Peter Jackson",
        "Rob Minkoff",
        "Roger Allers",
        "Roman Polanski",
        "Sam Raimi",
        "Steven Spielberg",
        "Vicky Jenson"
    };
}