namespace Common.Constants;

public class TagLists
{
    public List<string> GenreList { get; } = new()
    {
        "18th century",
        "19th century",
        "20th century",
        "academic",
        "action",
        "adventure",
        "africa",
        "african american",
        "african literature",
        "aliens",
        "alternate history",
        "american",
        "american civil war",
        "american history",
        "american revolution",
        "ancient",
        "ancient history",
        "angels",
        "animals",
        "anthologies",
        "anthropology",
        "apocalyptic",
        "art",
        "arthurian",
        "asia",
        "asian literature",
        "astronomy",
        "atheism",
        "australia",
        "autobiography",
        "aviation",
        "banned books",
        "biblical",
        "biblical fiction",
        "biography",
        "biography memoir",
        "biology",
        "book club",
        "books about books",
        "botswana",
        "british literature",
        "buddhism",
        "business",
        "canada",
        "cats",
        "chapter books",
        "chick lit",
        "childrens",
        "childrens classics",
        "china",
        "christian",
        "christian fiction",
        "christian romance",
        "christianity",
        "christmas",
        "church",
        "civil war",
        "classic literature",
        "classics",
        "collections",
        "college",
        "comedy",
        "comic book",
        "comic strips",
        "comics",
        "coming of age",
        "communication",
        "contemporary",
        "contemporary romance",
        "cooking",
        "counting",
        "crime",
        "cyberpunk",
        "czech literature",
        "dark",
        "death",
        "demons",
        "detective",
        "dinosaurs",
        "disability",
        "dogs",
        "dragons",
        "drama",
        "dystopia",
        "eastern philosophy",
        "economics",
        "education",
        "egypt",
        "english literature",
        "environment",
        "epic",
        "epic fantasy",
        "espionage",
        "essays",
        "ethiopia",
        "european history",
        "evolution",
        "fae",
        "fairies",
        "fairy tales",
        "faith",
        "family",
        "fantasy",
        "feminism",
        "fiction",
        "fighters",
        "finance",
        "folklore",
        "food",
        "france",
        "french literature",
        "french revolution",
        "futuristic",
        "gender",
        "german literature",
        "germany",
        "ghosts",
        "gothic",
        "graphic novels",
        "graphic novels comics",
        "greece",
        "greek mythology",
        "halloween",
        "health",
        "high fantasy",
        "high school",
        "historical",
        "historical fiction",
        "historical romance",
        "history",
        "holiday",
        "holocaust",
        "horror",
        "horse racing",
        "horses",
        "humor",
        "india",
        "indian literature",
        "inspirational",
        "ireland",
        "irish literature",
        "islam",
        "israel",
        "italian literature",
        "italy",
        "japan",
        "japanese literature",
        "jewish",
        "journalism",
        "judaism",
        "juvenile",
        "kids",
        "latin american",
        "law",
        "lds",
        "leadership",
        "legal thriller",
        "lgbt",
        "literary fiction",
        "literature",
        "love",
        "love story",
        "magic",
        "magical realism",
        "management",
        "mathematics",
        "media tie in",
        "medical",
        "medicine",
        "medieval",
        "memoir",
        "mental health",
        "mental illness",
        "middle grade",
        "military fiction",
        "modern classics",
        "monsters",
        "mountaineering",
        "music",
        "mystery",
        "mystery thriller",
        "mythology",
        "native americans",
        "nature",
        "new adult",
        "new age",
        "new york",
        "nigeria",
        "nobel prize",
        "noir",
        "nonfiction",
        "novels",
        "nutrition",
        "pakistan",
        "paranormal",
        "paranormal romance",
        "personal development",
        "philosophy",
        "physics",
        "picture books",
        "pirates",
        "plays",
        "poetry",
        "political science",
        "politics",
        "popular science",
        "portugal",
        "portuguese literature",
        "post apocalyptic",
        "prehistoric",
        "presidents",
        "productivity",
        "psychological thriller",
        "psychology",
        "queer",
        "race",
        "read for school",
        "realistic fiction",
        "reference",
        "regency",
        "relationships",
        "religion",
        "retellings",
        "road trip",
        "robots",
        "romance",
        "romanticism",
        "russia",
        "russian literature",
        "scandinavian literature",
        "school",
        "science",
        "science fiction",
        "science fiction fantasy",
        "scotland",
        "self help",
        "short stories",
        "social justice",
        "social science",
        "sociology",
        "south africa",
        "southern",
        "southern gothic",
        "space",
        "space opera",
        "spain",
        "spanish literature",
        "speculative fiction",
        "spirituality",
        "sports",
        "steampunk",
        "storytime",
        "superheroes",
        "supernatural",
        "survival",
        "suspense",
        "sweden",
        "swedish literature",
        "taoism",
        "teen",
        "the united states of america",
        "theatre",
        "theology",
        "theory",
        "thriller",
        "time travel",
        "tragedy",
        "travel",
        "travelogue",
        "true crime",
        "true story",
        "tudor period",
        "unfinished",
        "unicorns",
        "urban fantasy",
        "vampires",
        "victorian",
        "war",
        "werewolves",
        "westerns",
        "witches",
        "womens",
        "world war i",
        "world war ii",
        "writing",
        "young adult",
        "young adult contemporary",
        "young adult fantasy",
        "young adult romance",
        "zombies"
    };
}